[server]
headless = true

# Streamlit Cloud automatically sets the correct port,
# so we only set a fallback value for local environment.
port = 8501

# This enables full screen use in cloud environments
enableCORS = false
enableXsrfProtection = false
